
language: node_js
node_js:
  - "8"
  - "9"
cache:
  directories:
    - node_modules
install:
  - npm install

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test
    - stage: coverage
      script: npm run coveralls
